### ISSUE TITLE
a problem about model prediction

### ISSUE THREAD

**Issue by zxfzqf** [zhangyaqiang/lipreading#1]
hi，你好，我英语不太好，怕词不达意，希望不介意我用中文。
我刚开始使用tensorflow, dataload 方便参考你的这个项目的代码，确实训练速度比直接加载文件快，感谢!

但是这么直接把把数据迭代器的返回的tensor 直接用作输入数据（模型定义文件，build_inputs 函数）,而没有定义占位符，把输入定义为一个动态shape的tensor, 怎么做单个数据的predict？
我在加载模型做预测时，遇到期望获取（64，50，50，3）shape的张量的错误，64是训练时的batch_size，正常应该是期望（？，50，50，3）
你是怎么做单个数据的预测的？
先谢谢了！

**Comment by zhangyaqiang** [comment]
更新了

**Comment by zxfzqf** [comment]
原来是重新定义计算图，谢谢，麻烦了
